name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.6.21355.2'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal
    - name: Install Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.8.8
    - name: Generate Code Coverage Report
      run: reportgenerator "-reports:**/*.xml" "-targetdir:coveragereport" -reporttypes:HTMLInline
